# Generated by Django 4.2.5 on 2023-09-10 10:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "news_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("assigned_to_uuid", models.UUIDField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("news_text", models.CharField(max_length=1000)),
            ],
        ),
    ]
